// This file is generated by SQLBoiler (https://github.com/databrary/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// EDIT AT YOUR OWN RISK

package public

import (
	"bytes"
	"database/sql"
	"fmt"
	"github.com/databrary/sqlboiler/boil"
	"github.com/databrary/sqlboiler/queries"
	"github.com/databrary/sqlboiler/queries/qm"
	"github.com/databrary/sqlboiler/strmangle"
	"github.com/pkg/errors"
	"reflect"
	"strings"
	"sync"
	"time"
)

// Record is an object representing the database table.
type Record struct {
	ID       int   `db:"id" json:"record_id"`
	Volume   int   `db:"volume" json:"record_volume"`
	Category int16 `db:"category" json:"record_category"`

	R *recordR `db:"-" json:"-"`
	L recordL  `db:"-" json:"-"`
}

// recordR is where relationships are stored.
type recordR struct {
	Category        *Category
	Volume          *Volume
	IDRecordMeasure *RecordMeasure
	Metrics         MetricSlice
	MeasureDates    MeasureDateSlice
	MeasureNumerics MeasureNumericSlice
	MeasureTexts    MeasureTextSlice
	SlotRecords     SlotRecordSlice
}

// recordL is where Load methods for each relationship are stored.
type recordL struct{}

var (
	recordColumns               = []string{"id", "volume", "category"}
	recordColumnsWithoutDefault = []string{"volume", "category"}
	recordColumnsWithDefault    = []string{"id"}
	recordColumnsWithCustom     = []string{}

	recordPrimaryKeyColumns = []string{"id"}
)

type (
	// RecordSlice is an alias for a slice of pointers to Record.
	// This should generally be used opposed to []Record.
	RecordSlice []*Record
	// RecordHook is the signature for custom Record hook methods
	RecordHook func(boil.Executor, *Record) error

	recordQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	recordType    = reflect.TypeOf(&Record{})
	recordMapping = queries.MakeStructMapping(recordType)

	recordPrimaryKeyMapping, _ = queries.BindMapping(recordType, recordMapping, recordPrimaryKeyColumns)

	recordInsertCacheMut sync.RWMutex
	recordInsertCache    = make(map[string]insertCache)
	recordUpdateCacheMut sync.RWMutex
	recordUpdateCache    = make(map[string]updateCache)
	recordUpsertCacheMut sync.RWMutex
	recordUpsertCache    = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var recordBeforeInsertHooks []RecordHook
var recordBeforeUpdateHooks []RecordHook
var recordBeforeDeleteHooks []RecordHook
var recordBeforeUpsertHooks []RecordHook

var recordAfterInsertHooks []RecordHook
var recordAfterSelectHooks []RecordHook
var recordAfterUpdateHooks []RecordHook
var recordAfterDeleteHooks []RecordHook
var recordAfterUpsertHooks []RecordHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Record) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range recordBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Record) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range recordBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Record) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range recordBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Record) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range recordBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Record) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range recordAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Record) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range recordAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Record) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range recordAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Record) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range recordAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Record) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range recordAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddRecordHook registers your hook function for all future operations.
func AddRecordHook(hookPoint boil.HookPoint, recordHook RecordHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		recordBeforeInsertHooks = append(recordBeforeInsertHooks, recordHook)
	case boil.BeforeUpdateHook:
		recordBeforeUpdateHooks = append(recordBeforeUpdateHooks, recordHook)
	case boil.BeforeDeleteHook:
		recordBeforeDeleteHooks = append(recordBeforeDeleteHooks, recordHook)
	case boil.BeforeUpsertHook:
		recordBeforeUpsertHooks = append(recordBeforeUpsertHooks, recordHook)
	case boil.AfterInsertHook:
		recordAfterInsertHooks = append(recordAfterInsertHooks, recordHook)
	case boil.AfterSelectHook:
		recordAfterSelectHooks = append(recordAfterSelectHooks, recordHook)
	case boil.AfterUpdateHook:
		recordAfterUpdateHooks = append(recordAfterUpdateHooks, recordHook)
	case boil.AfterDeleteHook:
		recordAfterDeleteHooks = append(recordAfterDeleteHooks, recordHook)
	case boil.AfterUpsertHook:
		recordAfterUpsertHooks = append(recordAfterUpsertHooks, recordHook)
	}
}

// OneP returns a single record record from the query, and panics on error.
func (q recordQuery) OneP() *Record {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single record record from the query.
func (q recordQuery) One() (*Record, error) {
	o := &Record{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "public: failed to execute a one query for record")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all Record records from the query, and panics on error.
func (q recordQuery) AllP() RecordSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Record records from the query.
func (q recordQuery) All() (RecordSlice, error) {
	var o RecordSlice

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "public: failed to assign all query results to Record slice")
	}

	if len(recordAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all Record records in the query, and panics on error.
func (q recordQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Record records in the query.
func (q recordQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "public: failed to count record rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q recordQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q recordQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "public: failed to check if record exists")
	}

	return count > 0, nil
}

// CategoryG pointed to by the foreign key.
func (o *Record) CategoryG(mods ...qm.QueryMod) categoryQuery {
	return o.CategoryByFk(boil.GetDB(), mods...)
}

// Category pointed to by the foreign key.
func (o *Record) CategoryByFk(exec boil.Executor, mods ...qm.QueryMod) categoryQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.Category),
	}

	queryMods = append(queryMods, mods...)

	query := Categories(exec, queryMods...)
	queries.SetFrom(query.Query, "\"category\"")

	return query
}

// VolumeG pointed to by the foreign key.
func (o *Record) VolumeG(mods ...qm.QueryMod) volumeQuery {
	return o.VolumeByFk(boil.GetDB(), mods...)
}

// Volume pointed to by the foreign key.
func (o *Record) VolumeByFk(exec boil.Executor, mods ...qm.QueryMod) volumeQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.Volume),
	}

	queryMods = append(queryMods, mods...)

	query := Volumes(exec, queryMods...)
	queries.SetFrom(query.Query, "\"volume\"")

	return query
}

// IDRecordMeasureG pointed to by the foreign key.
func (o *Record) IDRecordMeasureG(mods ...qm.QueryMod) recordMeasureQuery {
	return o.IDRecordMeasureByFk(boil.GetDB(), mods...)
}

// IDRecordMeasure pointed to by the foreign key.
func (o *Record) IDRecordMeasureByFk(exec boil.Executor, mods ...qm.QueryMod) recordMeasureQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.ID),
	}

	queryMods = append(queryMods, mods...)

	query := RecordMeasures(exec, queryMods...)
	queries.SetFrom(query.Query, "\"record_measures\"")

	return query
}

// MetricsG retrieves all the metric's metric.
func (o *Record) MetricsG(mods ...qm.QueryMod) metricQuery {
	return o.MetricsByFk(boil.GetDB(), mods...)
}

// Metrics retrieves all the metric's metric with an executor.
func (o *Record) MetricsByFk(exec boil.Executor, mods ...qm.QueryMod) metricQuery {
	queryMods := []qm.QueryMod{
		qm.Select("\"a\".*"),
	}

	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.InnerJoin("\"measure_abstract\" as \"b\" on \"a\".\"id\" = \"b\".\"metric\""),
		qm.Where("\"b\".\"record\"=?", o.ID),
	)

	query := Metrics(exec, queryMods...)
	queries.SetFrom(query.Query, "\"metric\" as \"a\"")
	return query
}

// MeasureDatesG retrieves all the measure_date's measure date.
func (o *Record) MeasureDatesG(mods ...qm.QueryMod) measureDateQuery {
	return o.MeasureDatesByFk(boil.GetDB(), mods...)
}

// MeasureDates retrieves all the measure_date's measure date with an executor.
func (o *Record) MeasureDatesByFk(exec boil.Executor, mods ...qm.QueryMod) measureDateQuery {
	queryMods := []qm.QueryMod{
		qm.Select("\"a\".*"),
	}

	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"a\".\"record\"=?", o.ID),
	)

	query := MeasureDates(exec, queryMods...)
	queries.SetFrom(query.Query, "\"measure_date\" as \"a\"")
	return query
}

// MeasureNumericsG retrieves all the measure_numeric's measure numeric.
func (o *Record) MeasureNumericsG(mods ...qm.QueryMod) measureNumericQuery {
	return o.MeasureNumericsByFk(boil.GetDB(), mods...)
}

// MeasureNumerics retrieves all the measure_numeric's measure numeric with an executor.
func (o *Record) MeasureNumericsByFk(exec boil.Executor, mods ...qm.QueryMod) measureNumericQuery {
	queryMods := []qm.QueryMod{
		qm.Select("\"a\".*"),
	}

	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"a\".\"record\"=?", o.ID),
	)

	query := MeasureNumerics(exec, queryMods...)
	queries.SetFrom(query.Query, "\"measure_numeric\" as \"a\"")
	return query
}

// MeasureTextsG retrieves all the measure_text's measure text.
func (o *Record) MeasureTextsG(mods ...qm.QueryMod) measureTextQuery {
	return o.MeasureTextsByFk(boil.GetDB(), mods...)
}

// MeasureTexts retrieves all the measure_text's measure text with an executor.
func (o *Record) MeasureTextsByFk(exec boil.Executor, mods ...qm.QueryMod) measureTextQuery {
	queryMods := []qm.QueryMod{
		qm.Select("\"a\".*"),
	}

	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"a\".\"record\"=?", o.ID),
	)

	query := MeasureTexts(exec, queryMods...)
	queries.SetFrom(query.Query, "\"measure_text\" as \"a\"")
	return query
}

// SlotRecordsG retrieves all the slot_record's slot record.
func (o *Record) SlotRecordsG(mods ...qm.QueryMod) slotRecordQuery {
	return o.SlotRecordsByFk(boil.GetDB(), mods...)
}

// SlotRecords retrieves all the slot_record's slot record with an executor.
func (o *Record) SlotRecordsByFk(exec boil.Executor, mods ...qm.QueryMod) slotRecordQuery {
	queryMods := []qm.QueryMod{
		qm.Select("\"a\".*"),
	}

	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"a\".\"record\"=?", o.ID),
	)

	query := SlotRecords(exec, queryMods...)
	queries.SetFrom(query.Query, "\"slot_record\" as \"a\"")
	return query
}

// LoadCategory allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (recordL) LoadCategory(e boil.Executor, singular bool, maybeRecord interface{}) error {
	var slice []*Record
	var object *Record

	count := 1
	if singular {
		object = maybeRecord.(*Record)
	} else {
		slice = *maybeRecord.(*RecordSlice)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &recordR{}
		}
		args[0] = object.Category
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &recordR{}
			}
			args[i] = obj.Category
		}
	}

	query := fmt.Sprintf(
		"select * from \"category\" where \"id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Category")
	}
	defer results.Close()

	var resultSlice []*Category
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Category")
	}

	if len(recordAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.Category = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.Category == foreign.ID {
				local.R.Category = foreign
				break
			}
		}
	}

	return nil
}

// LoadVolume allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (recordL) LoadVolume(e boil.Executor, singular bool, maybeRecord interface{}) error {
	var slice []*Record
	var object *Record

	count := 1
	if singular {
		object = maybeRecord.(*Record)
	} else {
		slice = *maybeRecord.(*RecordSlice)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &recordR{}
		}
		args[0] = object.Volume
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &recordR{}
			}
			args[i] = obj.Volume
		}
	}

	query := fmt.Sprintf(
		"select * from \"volume\" where \"id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Volume")
	}
	defer results.Close()

	var resultSlice []*Volume
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Volume")
	}

	if len(recordAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.Volume = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.Volume == foreign.ID {
				local.R.Volume = foreign
				break
			}
		}
	}

	return nil
}

// LoadIDRecordMeasure allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (recordL) LoadIDRecordMeasure(e boil.Executor, singular bool, maybeRecord interface{}) error {
	var slice []*Record
	var object *Record

	count := 1
	if singular {
		object = maybeRecord.(*Record)
	} else {
		slice = *maybeRecord.(*RecordSlice)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &recordR{}
		}
		args[0] = object.ID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &recordR{}
			}
			args[i] = obj.ID
		}
	}

	query := fmt.Sprintf(
		"select * from \"record_measures\" where \"id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load RecordMeasure")
	}
	defer results.Close()

	var resultSlice []*RecordMeasure
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice RecordMeasure")
	}

	if len(recordAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.IDRecordMeasure = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ID == foreign.ID {
				local.R.IDRecordMeasure = foreign
				break
			}
		}
	}

	return nil
}

// LoadMetrics allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (recordL) LoadMetrics(e boil.Executor, singular bool, maybeRecord interface{}) error {
	var slice []*Record
	var object *Record

	count := 1
	if singular {
		object = maybeRecord.(*Record)
	} else {
		slice = *maybeRecord.(*RecordSlice)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &recordR{}
		}
		args[0] = object.ID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &recordR{}
			}
			args[i] = obj.ID
		}
	}

	query := fmt.Sprintf(
		"select \"a\".*, \"b\".\"record\" from \"metric\" as \"a\" inner join \"measure_abstract\" as \"b\" on \"a\".\"id\" = \"b\".\"metric\" where \"b\".\"record\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load metric")
	}
	defer results.Close()

	var resultSlice []*Metric

	var localJoinCols []int
	for results.Next() {
		one := new(Metric)
		var localJoinCol int

		err = results.Scan(&one.ID, &one.Category, &one.Name, &one.Release, &one.Type, &one.Options, &one.Assumed, &one.Description, &one.Required, &localJoinCol)
		if err = results.Err(); err != nil {
			return errors.Wrap(err, "failed to plebian-bind eager loaded slice metric")
		}

		resultSlice = append(resultSlice, one)
		localJoinCols = append(localJoinCols, localJoinCol)
	}

	if err = results.Err(); err != nil {
		return errors.Wrap(err, "failed to plebian-bind eager loaded slice metric")
	}

	if len(metricAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Metrics = resultSlice
		return nil
	}

	for i, foreign := range resultSlice {
		localJoinCol := localJoinCols[i]
		for _, local := range slice {
			if local.ID == localJoinCol {
				local.R.Metrics = append(local.R.Metrics, foreign)
				break
			}
		}
	}

	return nil
}

// LoadMeasureDates allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (recordL) LoadMeasureDates(e boil.Executor, singular bool, maybeRecord interface{}) error {
	var slice []*Record
	var object *Record

	count := 1
	if singular {
		object = maybeRecord.(*Record)
	} else {
		slice = *maybeRecord.(*RecordSlice)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &recordR{}
		}
		args[0] = object.ID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &recordR{}
			}
			args[i] = obj.ID
		}
	}

	query := fmt.Sprintf(
		"select * from \"measure_date\" where \"record\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load measure_date")
	}
	defer results.Close()

	var resultSlice []*MeasureDate
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice measure_date")
	}

	if len(measureDateAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.MeasureDates = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.Record {
				local.R.MeasureDates = append(local.R.MeasureDates, foreign)
				break
			}
		}
	}

	return nil
}

// LoadMeasureNumerics allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (recordL) LoadMeasureNumerics(e boil.Executor, singular bool, maybeRecord interface{}) error {
	var slice []*Record
	var object *Record

	count := 1
	if singular {
		object = maybeRecord.(*Record)
	} else {
		slice = *maybeRecord.(*RecordSlice)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &recordR{}
		}
		args[0] = object.ID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &recordR{}
			}
			args[i] = obj.ID
		}
	}

	query := fmt.Sprintf(
		"select * from \"measure_numeric\" where \"record\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load measure_numeric")
	}
	defer results.Close()

	var resultSlice []*MeasureNumeric
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice measure_numeric")
	}

	if len(measureNumericAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.MeasureNumerics = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.Record {
				local.R.MeasureNumerics = append(local.R.MeasureNumerics, foreign)
				break
			}
		}
	}

	return nil
}

// LoadMeasureTexts allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (recordL) LoadMeasureTexts(e boil.Executor, singular bool, maybeRecord interface{}) error {
	var slice []*Record
	var object *Record

	count := 1
	if singular {
		object = maybeRecord.(*Record)
	} else {
		slice = *maybeRecord.(*RecordSlice)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &recordR{}
		}
		args[0] = object.ID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &recordR{}
			}
			args[i] = obj.ID
		}
	}

	query := fmt.Sprintf(
		"select * from \"measure_text\" where \"record\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load measure_text")
	}
	defer results.Close()

	var resultSlice []*MeasureText
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice measure_text")
	}

	if len(measureTextAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.MeasureTexts = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.Record {
				local.R.MeasureTexts = append(local.R.MeasureTexts, foreign)
				break
			}
		}
	}

	return nil
}

// LoadSlotRecords allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (recordL) LoadSlotRecords(e boil.Executor, singular bool, maybeRecord interface{}) error {
	var slice []*Record
	var object *Record

	count := 1
	if singular {
		object = maybeRecord.(*Record)
	} else {
		slice = *maybeRecord.(*RecordSlice)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &recordR{}
		}
		args[0] = object.ID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &recordR{}
			}
			args[i] = obj.ID
		}
	}

	query := fmt.Sprintf(
		"select * from \"slot_record\" where \"record\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load slot_record")
	}
	defer results.Close()

	var resultSlice []*SlotRecord
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice slot_record")
	}

	if len(slotRecordAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.SlotRecords = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.Record {
				local.R.SlotRecords = append(local.R.SlotRecords, foreign)
				break
			}
		}
	}

	return nil
}

// SetCategoryG of the record to the related item.
// Sets o.R.Category to related.
// Adds o to related.R.Records.
// Uses the global database handle.
func (o *Record) SetCategoryG(insert bool, related *Category) error {
	return o.SetCategory(boil.GetDB(), insert, related)
}

// SetCategoryP of the record to the related item.
// Sets o.R.Category to related.
// Adds o to related.R.Records.
// Panics on error.
func (o *Record) SetCategoryP(exec boil.Executor, insert bool, related *Category) {
	if err := o.SetCategory(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetCategoryGP of the record to the related item.
// Sets o.R.Category to related.
// Adds o to related.R.Records.
// Uses the global database handle and panics on error.
func (o *Record) SetCategoryGP(insert bool, related *Category) {
	if err := o.SetCategory(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetCategory of the record to the related item.
// Sets o.R.Category to related.
// Adds o to related.R.Records.
func (o *Record) SetCategory(exec boil.Executor, insert bool, related *Category) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"record\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"category"}),
		strmangle.WhereClause("\"", "\"", 2, recordPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.Category = related.ID

	if o.R == nil {
		o.R = &recordR{
			Category: related,
		}
	} else {
		o.R.Category = related
	}

	if related.R == nil {
		related.R = &categoryR{
			Records: RecordSlice{o},
		}
	} else {
		related.R.Records = append(related.R.Records, o)
	}

	return nil
}

// SetVolumeG of the record to the related item.
// Sets o.R.Volume to related.
// Adds o to related.R.Records.
// Uses the global database handle.
func (o *Record) SetVolumeG(insert bool, related *Volume) error {
	return o.SetVolume(boil.GetDB(), insert, related)
}

// SetVolumeP of the record to the related item.
// Sets o.R.Volume to related.
// Adds o to related.R.Records.
// Panics on error.
func (o *Record) SetVolumeP(exec boil.Executor, insert bool, related *Volume) {
	if err := o.SetVolume(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetVolumeGP of the record to the related item.
// Sets o.R.Volume to related.
// Adds o to related.R.Records.
// Uses the global database handle and panics on error.
func (o *Record) SetVolumeGP(insert bool, related *Volume) {
	if err := o.SetVolume(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetVolume of the record to the related item.
// Sets o.R.Volume to related.
// Adds o to related.R.Records.
func (o *Record) SetVolume(exec boil.Executor, insert bool, related *Volume) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"record\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"volume"}),
		strmangle.WhereClause("\"", "\"", 2, recordPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.Volume = related.ID

	if o.R == nil {
		o.R = &recordR{
			Volume: related,
		}
	} else {
		o.R.Volume = related
	}

	if related.R == nil {
		related.R = &volumeR{
			Records: RecordSlice{o},
		}
	} else {
		related.R.Records = append(related.R.Records, o)
	}

	return nil
}

// SetIDRecordMeasureG of the record to the related item.
// Sets o.R.IDRecordMeasure to related.
// Adds o to related.R.ID.
// Uses the global database handle.
func (o *Record) SetIDRecordMeasureG(insert bool, related *RecordMeasure) error {
	return o.SetIDRecordMeasure(boil.GetDB(), insert, related)
}

// SetIDRecordMeasureP of the record to the related item.
// Sets o.R.IDRecordMeasure to related.
// Adds o to related.R.ID.
// Panics on error.
func (o *Record) SetIDRecordMeasureP(exec boil.Executor, insert bool, related *RecordMeasure) {
	if err := o.SetIDRecordMeasure(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetIDRecordMeasureGP of the record to the related item.
// Sets o.R.IDRecordMeasure to related.
// Adds o to related.R.ID.
// Uses the global database handle and panics on error.
func (o *Record) SetIDRecordMeasureGP(insert bool, related *RecordMeasure) {
	if err := o.SetIDRecordMeasure(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetIDRecordMeasure of the record to the related item.
// Sets o.R.IDRecordMeasure to related.
// Adds o to related.R.ID.
func (o *Record) SetIDRecordMeasure(exec boil.Executor, insert bool, related *RecordMeasure) error {
	var err error

	if insert {
		related.ID = o.ID

		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	} else {
		updateQuery := fmt.Sprintf(
			"UPDATE \"record_measures\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, []string{"id"}),
			strmangle.WhereClause("\"", "\"", 2, recordMeasurePrimaryKeyColumns),
		)
		values := []interface{}{o.ID, related.ID}

		if boil.DebugMode {
			fmt.Fprintln(boil.DebugWriter, updateQuery)
			fmt.Fprintln(boil.DebugWriter, values)
		}

		if _, err = exec.Exec(updateQuery, values...); err != nil {
			return errors.Wrap(err, "failed to update foreign table")
		}

		related.ID = o.ID

	}

	if o.R == nil {
		o.R = &recordR{
			IDRecordMeasure: related,
		}
	} else {
		o.R.IDRecordMeasure = related
	}

	if related.R == nil {
		related.R = &recordMeasureR{
			ID: o,
		}
	} else {
		related.R.ID = o
	}
	return nil
}

// AddMetricsG adds the given related objects to the existing relationships
// of the record, optionally inserting them as new records.
// Appends related to o.R.Metrics.
// Sets related.R.Records appropriately.
// Uses the global database handle.
func (o *Record) AddMetricsG(insert bool, related ...*Metric) error {
	return o.AddMetrics(boil.GetDB(), insert, related...)
}

// AddMetricsP adds the given related objects to the existing relationships
// of the record, optionally inserting them as new records.
// Appends related to o.R.Metrics.
// Sets related.R.Records appropriately.
// Panics on error.
func (o *Record) AddMetricsP(exec boil.Executor, insert bool, related ...*Metric) {
	if err := o.AddMetrics(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddMetricsGP adds the given related objects to the existing relationships
// of the record, optionally inserting them as new records.
// Appends related to o.R.Metrics.
// Sets related.R.Records appropriately.
// Uses the global database handle and panics on error.
func (o *Record) AddMetricsGP(insert bool, related ...*Metric) {
	if err := o.AddMetrics(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddMetrics adds the given related objects to the existing relationships
// of the record, optionally inserting them as new records.
// Appends related to o.R.Metrics.
// Sets related.R.Records appropriately.
func (o *Record) AddMetrics(exec boil.Executor, insert bool, related ...*Metric) error {
	var err error
	for _, rel := range related {
		if insert {
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		}
	}

	for _, rel := range related {
		query := "insert into \"measure_abstract\" (\"record\", \"metric\") values ($1, $2)"
		values := []interface{}{o.ID, rel.ID}

		if boil.DebugMode {
			fmt.Fprintln(boil.DebugWriter, query)
			fmt.Fprintln(boil.DebugWriter, values)
		}

		_, err = exec.Exec(query, values...)
		if err != nil {
			return errors.Wrap(err, "failed to insert into join table")
		}
	}
	if o.R == nil {
		o.R = &recordR{
			Metrics: related,
		}
	} else {
		o.R.Metrics = append(o.R.Metrics, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &metricR{
				Records: RecordSlice{o},
			}
		} else {
			rel.R.Records = append(rel.R.Records, o)
		}
	}
	return nil
}

// SetMetricsG removes all previously related items of the
// record replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Records's Metrics accordingly.
// Replaces o.R.Metrics with related.
// Sets related.R.Records's Metrics accordingly.
// Uses the global database handle.
func (o *Record) SetMetricsG(insert bool, related ...*Metric) error {
	return o.SetMetrics(boil.GetDB(), insert, related...)
}

// SetMetricsP removes all previously related items of the
// record replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Records's Metrics accordingly.
// Replaces o.R.Metrics with related.
// Sets related.R.Records's Metrics accordingly.
// Panics on error.
func (o *Record) SetMetricsP(exec boil.Executor, insert bool, related ...*Metric) {
	if err := o.SetMetrics(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetMetricsGP removes all previously related items of the
// record replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Records's Metrics accordingly.
// Replaces o.R.Metrics with related.
// Sets related.R.Records's Metrics accordingly.
// Uses the global database handle and panics on error.
func (o *Record) SetMetricsGP(insert bool, related ...*Metric) {
	if err := o.SetMetrics(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetMetrics removes all previously related items of the
// record replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Records's Metrics accordingly.
// Replaces o.R.Metrics with related.
// Sets related.R.Records's Metrics accordingly.
func (o *Record) SetMetrics(exec boil.Executor, insert bool, related ...*Metric) error {
	query := "delete from \"measure_abstract\" where \"record\" = $1"
	values := []interface{}{o.ID}
	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err := exec.Exec(query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	removeMetricsFromRecordsSlice(o, related)
	if o.R != nil {
		o.R.Metrics = nil
	}
	return o.AddMetrics(exec, insert, related...)
}

// RemoveMetricsG relationships from objects passed in.
// Removes related items from R.Metrics (uses pointer comparison, removal does not keep order)
// Sets related.R.Records.
// Uses the global database handle.
func (o *Record) RemoveMetricsG(related ...*Metric) error {
	return o.RemoveMetrics(boil.GetDB(), related...)
}

// RemoveMetricsP relationships from objects passed in.
// Removes related items from R.Metrics (uses pointer comparison, removal does not keep order)
// Sets related.R.Records.
// Panics on error.
func (o *Record) RemoveMetricsP(exec boil.Executor, related ...*Metric) {
	if err := o.RemoveMetrics(exec, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveMetricsGP relationships from objects passed in.
// Removes related items from R.Metrics (uses pointer comparison, removal does not keep order)
// Sets related.R.Records.
// Uses the global database handle and panics on error.
func (o *Record) RemoveMetricsGP(related ...*Metric) {
	if err := o.RemoveMetrics(boil.GetDB(), related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveMetrics relationships from objects passed in.
// Removes related items from R.Metrics (uses pointer comparison, removal does not keep order)
// Sets related.R.Records.
func (o *Record) RemoveMetrics(exec boil.Executor, related ...*Metric) error {
	var err error
	query := fmt.Sprintf(
		"delete from \"measure_abstract\" where \"record\" = $1 and \"metric\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, len(related), 2, 1),
	)
	values := []interface{}{o.ID}
	for _, rel := range related {
		values = append(values, rel.ID)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}
	removeMetricsFromRecordsSlice(o, related)
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.Metrics {
			if rel != ri {
				continue
			}

			ln := len(o.R.Metrics)
			if ln > 1 && i < ln-1 {
				o.R.Metrics[i] = o.R.Metrics[ln-1]
			}
			o.R.Metrics = o.R.Metrics[:ln-1]
			break
		}
	}

	return nil
}

func removeMetricsFromRecordsSlice(o *Record, related []*Metric) {
	for _, rel := range related {
		if rel.R == nil {
			continue
		}
		for i, ri := range rel.R.Records {
			if o.ID != ri.ID {
				continue
			}

			ln := len(rel.R.Records)
			if ln > 1 && i < ln-1 {
				rel.R.Records[i] = rel.R.Records[ln-1]
			}
			rel.R.Records = rel.R.Records[:ln-1]
			break
		}
	}
}

// AddMeasureDatesG adds the given related objects to the existing relationships
// of the record, optionally inserting them as new records.
// Appends related to o.R.MeasureDates.
// Sets related.R.Record appropriately.
// Uses the global database handle.
func (o *Record) AddMeasureDatesG(insert bool, related ...*MeasureDate) error {
	return o.AddMeasureDates(boil.GetDB(), insert, related...)
}

// AddMeasureDatesP adds the given related objects to the existing relationships
// of the record, optionally inserting them as new records.
// Appends related to o.R.MeasureDates.
// Sets related.R.Record appropriately.
// Panics on error.
func (o *Record) AddMeasureDatesP(exec boil.Executor, insert bool, related ...*MeasureDate) {
	if err := o.AddMeasureDates(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddMeasureDatesGP adds the given related objects to the existing relationships
// of the record, optionally inserting them as new records.
// Appends related to o.R.MeasureDates.
// Sets related.R.Record appropriately.
// Uses the global database handle and panics on error.
func (o *Record) AddMeasureDatesGP(insert bool, related ...*MeasureDate) {
	if err := o.AddMeasureDates(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddMeasureDates adds the given related objects to the existing relationships
// of the record, optionally inserting them as new records.
// Appends related to o.R.MeasureDates.
// Sets related.R.Record appropriately.
func (o *Record) AddMeasureDates(exec boil.Executor, insert bool, related ...*MeasureDate) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.Record = o.ID
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"measure_date\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"record"}),
				strmangle.WhereClause("\"", "\"", 2, measureDatePrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.Record, rel.Metric}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.Record = o.ID
		}
	}

	if o.R == nil {
		o.R = &recordR{
			MeasureDates: related,
		}
	} else {
		o.R.MeasureDates = append(o.R.MeasureDates, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &measureDateR{
				Record: o,
			}
		} else {
			rel.R.Record = o
		}
	}
	return nil
}

// AddMeasureNumericsG adds the given related objects to the existing relationships
// of the record, optionally inserting them as new records.
// Appends related to o.R.MeasureNumerics.
// Sets related.R.Record appropriately.
// Uses the global database handle.
func (o *Record) AddMeasureNumericsG(insert bool, related ...*MeasureNumeric) error {
	return o.AddMeasureNumerics(boil.GetDB(), insert, related...)
}

// AddMeasureNumericsP adds the given related objects to the existing relationships
// of the record, optionally inserting them as new records.
// Appends related to o.R.MeasureNumerics.
// Sets related.R.Record appropriately.
// Panics on error.
func (o *Record) AddMeasureNumericsP(exec boil.Executor, insert bool, related ...*MeasureNumeric) {
	if err := o.AddMeasureNumerics(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddMeasureNumericsGP adds the given related objects to the existing relationships
// of the record, optionally inserting them as new records.
// Appends related to o.R.MeasureNumerics.
// Sets related.R.Record appropriately.
// Uses the global database handle and panics on error.
func (o *Record) AddMeasureNumericsGP(insert bool, related ...*MeasureNumeric) {
	if err := o.AddMeasureNumerics(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddMeasureNumerics adds the given related objects to the existing relationships
// of the record, optionally inserting them as new records.
// Appends related to o.R.MeasureNumerics.
// Sets related.R.Record appropriately.
func (o *Record) AddMeasureNumerics(exec boil.Executor, insert bool, related ...*MeasureNumeric) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.Record = o.ID
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"measure_numeric\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"record"}),
				strmangle.WhereClause("\"", "\"", 2, measureNumericPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.Record, rel.Metric}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.Record = o.ID
		}
	}

	if o.R == nil {
		o.R = &recordR{
			MeasureNumerics: related,
		}
	} else {
		o.R.MeasureNumerics = append(o.R.MeasureNumerics, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &measureNumericR{
				Record: o,
			}
		} else {
			rel.R.Record = o
		}
	}
	return nil
}

// AddMeasureTextsG adds the given related objects to the existing relationships
// of the record, optionally inserting them as new records.
// Appends related to o.R.MeasureTexts.
// Sets related.R.Record appropriately.
// Uses the global database handle.
func (o *Record) AddMeasureTextsG(insert bool, related ...*MeasureText) error {
	return o.AddMeasureTexts(boil.GetDB(), insert, related...)
}

// AddMeasureTextsP adds the given related objects to the existing relationships
// of the record, optionally inserting them as new records.
// Appends related to o.R.MeasureTexts.
// Sets related.R.Record appropriately.
// Panics on error.
func (o *Record) AddMeasureTextsP(exec boil.Executor, insert bool, related ...*MeasureText) {
	if err := o.AddMeasureTexts(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddMeasureTextsGP adds the given related objects to the existing relationships
// of the record, optionally inserting them as new records.
// Appends related to o.R.MeasureTexts.
// Sets related.R.Record appropriately.
// Uses the global database handle and panics on error.
func (o *Record) AddMeasureTextsGP(insert bool, related ...*MeasureText) {
	if err := o.AddMeasureTexts(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddMeasureTexts adds the given related objects to the existing relationships
// of the record, optionally inserting them as new records.
// Appends related to o.R.MeasureTexts.
// Sets related.R.Record appropriately.
func (o *Record) AddMeasureTexts(exec boil.Executor, insert bool, related ...*MeasureText) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.Record = o.ID
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"measure_text\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"record"}),
				strmangle.WhereClause("\"", "\"", 2, measureTextPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.Record, rel.Metric}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.Record = o.ID
		}
	}

	if o.R == nil {
		o.R = &recordR{
			MeasureTexts: related,
		}
	} else {
		o.R.MeasureTexts = append(o.R.MeasureTexts, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &measureTextR{
				Record: o,
			}
		} else {
			rel.R.Record = o
		}
	}
	return nil
}

// AddSlotRecordsG adds the given related objects to the existing relationships
// of the record, optionally inserting them as new records.
// Appends related to o.R.SlotRecords.
// Sets related.R.Record appropriately.
// Uses the global database handle.
func (o *Record) AddSlotRecordsG(insert bool, related ...*SlotRecord) error {
	return o.AddSlotRecords(boil.GetDB(), insert, related...)
}

// AddSlotRecordsP adds the given related objects to the existing relationships
// of the record, optionally inserting them as new records.
// Appends related to o.R.SlotRecords.
// Sets related.R.Record appropriately.
// Panics on error.
func (o *Record) AddSlotRecordsP(exec boil.Executor, insert bool, related ...*SlotRecord) {
	if err := o.AddSlotRecords(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddSlotRecordsGP adds the given related objects to the existing relationships
// of the record, optionally inserting them as new records.
// Appends related to o.R.SlotRecords.
// Sets related.R.Record appropriately.
// Uses the global database handle and panics on error.
func (o *Record) AddSlotRecordsGP(insert bool, related ...*SlotRecord) {
	if err := o.AddSlotRecords(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddSlotRecords adds the given related objects to the existing relationships
// of the record, optionally inserting them as new records.
// Appends related to o.R.SlotRecords.
// Sets related.R.Record appropriately.
func (o *Record) AddSlotRecords(exec boil.Executor, insert bool, related ...*SlotRecord) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.Record = o.ID
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"slot_record\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"record"}),
				strmangle.WhereClause("\"", "\"", 2, slotRecordPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.Container, rel.Segment, rel.Record}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.Record = o.ID
		}
	}

	if o.R == nil {
		o.R = &recordR{
			SlotRecords: related,
		}
	} else {
		o.R.SlotRecords = append(o.R.SlotRecords, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &slotRecordR{
				Record: o,
			}
		} else {
			rel.R.Record = o
		}
	}
	return nil
}

// RecordsG retrieves all records.
func RecordsG(mods ...qm.QueryMod) recordQuery {
	return Records(boil.GetDB(), mods...)
}

// Records retrieves all the records using an executor.
func Records(exec boil.Executor, mods ...qm.QueryMod) recordQuery {
	mods = append(mods, qm.From("\"record\""))
	return recordQuery{NewQuery(exec, mods...)}
}

// FindRecordG retrieves a single record by ID.
func FindRecordG(id int, selectCols ...string) (*Record, error) {
	return FindRecord(boil.GetDB(), id, selectCols...)
}

// FindRecordGP retrieves a single record by ID, and panics on error.
func FindRecordGP(id int, selectCols ...string) *Record {
	retobj, err := FindRecord(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindRecord retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindRecord(exec boil.Executor, id int, selectCols ...string) (*Record, error) {
	recordObj := &Record{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"record\" where \"id\"=$1", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(recordObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "public: unable to select from record")
	}

	return recordObj, nil
}

// FindRecordP retrieves a single record by ID with an executor, and panics on error.
func FindRecordP(exec boil.Executor, id int, selectCols ...string) *Record {
	retobj, err := FindRecord(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Record) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Record) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Record) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *Record) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("public: no record provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(recordColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	recordInsertCacheMut.RLock()
	cache, cached := recordInsertCache[key]
	recordInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			recordColumns,
			recordColumnsWithDefault,
			recordColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(recordType, recordMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(recordType, recordMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"record\" (\"%s\") VALUES (%s)", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"record\" DEFAULT VALUES"
		}

		if len(cache.retMapping) != 0 {
			cache.query += fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "public: unable to insert into record")
	}

	if !cached {
		recordInsertCacheMut.Lock()
		recordInsertCache[key] = cache
		recordInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single Record record. See Update for
// whitelist behavior description.
func (o *Record) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single Record record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *Record) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the Record, and panics on error.
// See Update for whitelist behavior description.
func (o *Record) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the Record.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *Record) Update(exec boil.Executor, whitelist ...string) error {
	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	recordUpdateCacheMut.RLock()
	cache, cached := recordUpdateCache[key]
	recordUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(recordColumns, recordPrimaryKeyColumns, whitelist)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("public: unable to update record, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"record\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, recordPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(recordType, recordMapping, append(wl, recordPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "public: unable to update record row")
	}

	if !cached {
		recordUpdateCacheMut.Lock()
		recordUpdateCache[key] = cache
		recordUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q recordQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q recordQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "public: unable to update all for record")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o RecordSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o RecordSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o RecordSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o RecordSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("public: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), recordPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	query := fmt.Sprintf(
		"UPDATE \"record\" SET %s WHERE (\"id\") IN (%s)",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.Placeholders(dialect.IndexPlaceholders, len(o)*len(recordPrimaryKeyColumns), len(colNames)+1, len(recordPrimaryKeyColumns)),
	)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(query, args...)
	if err != nil {
		return errors.Wrap(err, "public: unable to update all in record slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Record) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Record) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Record) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *Record) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("public: no record provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(recordColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	recordUpsertCacheMut.RLock()
	cache, cached := recordUpsertCache[key]
	recordUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		var ret []string
		whitelist, ret = strmangle.InsertColumnSet(
			recordColumns,
			recordColumnsWithDefault,
			recordColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)
		update := strmangle.UpdateColumnSet(
			recordColumns,
			recordPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("public: unable to upsert record, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(recordPrimaryKeyColumns))
			copy(conflict, recordPrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"record\"", updateOnConflict, ret, update, conflict, whitelist)

		cache.valueMapping, err = queries.BindMapping(recordType, recordMapping, whitelist)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(recordType, recordMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "public: unable to upsert record")
	}

	if !cached {
		recordUpsertCacheMut.Lock()
		recordUpsertCache[key] = cache
		recordUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single Record record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Record) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single Record record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Record) DeleteG() error {
	if o == nil {
		return errors.New("public: no Record provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single Record record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Record) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single Record record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Record) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("public: no Record provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), recordPrimaryKeyMapping)
	query := "DELETE FROM \"record\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(query, args...)
	if err != nil {
		return errors.Wrap(err, "public: unable to delete from record")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q recordQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q recordQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("public: no recordQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "public: unable to delete all from record")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o RecordSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o RecordSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("public: no Record slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o RecordSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o RecordSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("public: no Record slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(recordBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), recordPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	query := fmt.Sprintf(
		"DELETE FROM \"record\" WHERE (%s) IN (%s)",
		strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, recordPrimaryKeyColumns), ","),
		strmangle.Placeholders(dialect.IndexPlaceholders, len(o)*len(recordPrimaryKeyColumns), 1, len(recordPrimaryKeyColumns)),
	)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(query, args...)
	if err != nil {
		return errors.Wrap(err, "public: unable to delete all from record slice")
	}

	if len(recordAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Record) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Record) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Record) ReloadG() error {
	if o == nil {
		return errors.New("public: no Record provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Record) Reload(exec boil.Executor) error {
	ret, err := FindRecord(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *RecordSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *RecordSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *RecordSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("public: empty RecordSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *RecordSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	records := RecordSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), recordPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	query := fmt.Sprintf(
		"SELECT \"record\".* FROM \"record\" WHERE (%s) IN (%s)",
		strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, recordPrimaryKeyColumns), ","),
		strmangle.Placeholders(dialect.IndexPlaceholders, len(*o)*len(recordPrimaryKeyColumns), 1, len(recordPrimaryKeyColumns)),
	)

	q := queries.Raw(exec, query, args...)

	err := q.Bind(&records)
	if err != nil {
		return errors.Wrap(err, "public: unable to reload all in RecordSlice")
	}

	*o = records

	return nil
}

// RecordExists checks if the Record row exists.
func RecordExists(exec boil.Executor, id int) (bool, error) {
	var exists bool

	query := "select exists(select 1 from \"record\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(query, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "public: unable to check if record exists")
	}

	return exists, nil
}

// RecordExistsG checks if the Record row exists.
func RecordExistsG(id int) (bool, error) {
	return RecordExists(boil.GetDB(), id)
}

// RecordExistsGP checks if the Record row exists. Panics on error.
func RecordExistsGP(id int) bool {
	e, err := RecordExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// RecordExistsP checks if the Record row exists. Panics on error.
func RecordExistsP(exec boil.Executor, id int) bool {
	e, err := RecordExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
