// This file is generated by SQLBoiler (https://github.com/databrary/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// EDIT AT YOUR OWN RISK

package public

import (
	"bytes"
	"database/sql"
	"fmt"
	"github.com/databrary/databrary/db/models/custom_types"
	"github.com/databrary/sqlboiler/boil"
	"github.com/databrary/sqlboiler/queries"
	"github.com/databrary/sqlboiler/queries/qm"
	"github.com/databrary/sqlboiler/strmangle"
	"github.com/pkg/errors"
	"reflect"
	"strings"
	"sync"
	"time"
)

// SlotRelease is an object representing the database table.
type SlotRelease struct {
	Container int                  `db:"container" json:"slotRelease_container"`
	Segment   custom_types.Segment `db:"segment" json:"slotRelease_segment"`
	Release   custom_types.Release `db:"release" json:"slotRelease_release"`

	R *slotReleaseR `db:"-" json:"-"`
	L slotReleaseL  `db:"-" json:"-"`
}

// slotReleaseR is where relationships are stored.
type slotReleaseR struct {
	Container *Container
}

// slotReleaseL is where Load methods for each relationship are stored.
type slotReleaseL struct{}

var (
	slotReleaseColumns               = []string{"container", "segment", "release"}
	slotReleaseColumnsWithoutDefault = []string{"container", "segment", "release"}
	slotReleaseColumnsWithDefault    = []string{}
	slotReleaseColumnsWithCustom     = []string{"segment", "release"}

	slotReleasePrimaryKeyColumns = []string{"container", "segment"}
)

type (
	// SlotReleaseSlice is an alias for a slice of pointers to SlotRelease.
	// This should generally be used opposed to []SlotRelease.
	SlotReleaseSlice []*SlotRelease
	// SlotReleaseHook is the signature for custom SlotRelease hook methods
	SlotReleaseHook func(boil.Executor, *SlotRelease) error

	slotReleaseQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	slotReleaseType    = reflect.TypeOf(&SlotRelease{})
	slotReleaseMapping = queries.MakeStructMapping(slotReleaseType)

	slotReleasePrimaryKeyMapping, _ = queries.BindMapping(slotReleaseType, slotReleaseMapping, slotReleasePrimaryKeyColumns)

	slotReleaseInsertCacheMut sync.RWMutex
	slotReleaseInsertCache    = make(map[string]insertCache)
	slotReleaseUpdateCacheMut sync.RWMutex
	slotReleaseUpdateCache    = make(map[string]updateCache)
	slotReleaseUpsertCacheMut sync.RWMutex
	slotReleaseUpsertCache    = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var slotReleaseBeforeInsertHooks []SlotReleaseHook
var slotReleaseBeforeUpdateHooks []SlotReleaseHook
var slotReleaseBeforeDeleteHooks []SlotReleaseHook
var slotReleaseBeforeUpsertHooks []SlotReleaseHook

var slotReleaseAfterInsertHooks []SlotReleaseHook
var slotReleaseAfterSelectHooks []SlotReleaseHook
var slotReleaseAfterUpdateHooks []SlotReleaseHook
var slotReleaseAfterDeleteHooks []SlotReleaseHook
var slotReleaseAfterUpsertHooks []SlotReleaseHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *SlotRelease) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range slotReleaseBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *SlotRelease) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range slotReleaseBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *SlotRelease) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range slotReleaseBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *SlotRelease) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range slotReleaseBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *SlotRelease) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range slotReleaseAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *SlotRelease) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range slotReleaseAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *SlotRelease) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range slotReleaseAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *SlotRelease) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range slotReleaseAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *SlotRelease) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range slotReleaseAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSlotReleaseHook registers your hook function for all future operations.
func AddSlotReleaseHook(hookPoint boil.HookPoint, slotReleaseHook SlotReleaseHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		slotReleaseBeforeInsertHooks = append(slotReleaseBeforeInsertHooks, slotReleaseHook)
	case boil.BeforeUpdateHook:
		slotReleaseBeforeUpdateHooks = append(slotReleaseBeforeUpdateHooks, slotReleaseHook)
	case boil.BeforeDeleteHook:
		slotReleaseBeforeDeleteHooks = append(slotReleaseBeforeDeleteHooks, slotReleaseHook)
	case boil.BeforeUpsertHook:
		slotReleaseBeforeUpsertHooks = append(slotReleaseBeforeUpsertHooks, slotReleaseHook)
	case boil.AfterInsertHook:
		slotReleaseAfterInsertHooks = append(slotReleaseAfterInsertHooks, slotReleaseHook)
	case boil.AfterSelectHook:
		slotReleaseAfterSelectHooks = append(slotReleaseAfterSelectHooks, slotReleaseHook)
	case boil.AfterUpdateHook:
		slotReleaseAfterUpdateHooks = append(slotReleaseAfterUpdateHooks, slotReleaseHook)
	case boil.AfterDeleteHook:
		slotReleaseAfterDeleteHooks = append(slotReleaseAfterDeleteHooks, slotReleaseHook)
	case boil.AfterUpsertHook:
		slotReleaseAfterUpsertHooks = append(slotReleaseAfterUpsertHooks, slotReleaseHook)
	}
}

// OneP returns a single slotRelease record from the query, and panics on error.
func (q slotReleaseQuery) OneP() *SlotRelease {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single slotRelease record from the query.
func (q slotReleaseQuery) One() (*SlotRelease, error) {
	o := &SlotRelease{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "public: failed to execute a one query for slot_release")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all SlotRelease records from the query, and panics on error.
func (q slotReleaseQuery) AllP() SlotReleaseSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all SlotRelease records from the query.
func (q slotReleaseQuery) All() (SlotReleaseSlice, error) {
	var o SlotReleaseSlice

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "public: failed to assign all query results to SlotRelease slice")
	}

	if len(slotReleaseAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all SlotRelease records in the query, and panics on error.
func (q slotReleaseQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all SlotRelease records in the query.
func (q slotReleaseQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "public: failed to count slot_release rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q slotReleaseQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q slotReleaseQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "public: failed to check if slot_release exists")
	}

	return count > 0, nil
}

// ContainerG pointed to by the foreign key.
func (o *SlotRelease) ContainerG(mods ...qm.QueryMod) containerQuery {
	return o.ContainerByFk(boil.GetDB(), mods...)
}

// Container pointed to by the foreign key.
func (o *SlotRelease) ContainerByFk(exec boil.Executor, mods ...qm.QueryMod) containerQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.Container),
	}

	queryMods = append(queryMods, mods...)

	query := Containers(exec, queryMods...)
	queries.SetFrom(query.Query, "\"container\"")

	return query
}

// LoadContainer allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (slotReleaseL) LoadContainer(e boil.Executor, singular bool, maybeSlotRelease interface{}) error {
	var slice []*SlotRelease
	var object *SlotRelease

	count := 1
	if singular {
		object = maybeSlotRelease.(*SlotRelease)
	} else {
		slice = *maybeSlotRelease.(*SlotReleaseSlice)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &slotReleaseR{}
		}
		args[0] = object.Container
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &slotReleaseR{}
			}
			args[i] = obj.Container
		}
	}

	query := fmt.Sprintf(
		"select * from \"container\" where \"id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Container")
	}
	defer results.Close()

	var resultSlice []*Container
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Container")
	}

	if len(slotReleaseAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.Container = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.Container == foreign.ID {
				local.R.Container = foreign
				break
			}
		}
	}

	return nil
}

// SetContainerG of the slot_release to the related item.
// Sets o.R.Container to related.
// Adds o to related.R.SlotReleases.
// Uses the global database handle.
func (o *SlotRelease) SetContainerG(insert bool, related *Container) error {
	return o.SetContainer(boil.GetDB(), insert, related)
}

// SetContainerP of the slot_release to the related item.
// Sets o.R.Container to related.
// Adds o to related.R.SlotReleases.
// Panics on error.
func (o *SlotRelease) SetContainerP(exec boil.Executor, insert bool, related *Container) {
	if err := o.SetContainer(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetContainerGP of the slot_release to the related item.
// Sets o.R.Container to related.
// Adds o to related.R.SlotReleases.
// Uses the global database handle and panics on error.
func (o *SlotRelease) SetContainerGP(insert bool, related *Container) {
	if err := o.SetContainer(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetContainer of the slot_release to the related item.
// Sets o.R.Container to related.
// Adds o to related.R.SlotReleases.
func (o *SlotRelease) SetContainer(exec boil.Executor, insert bool, related *Container) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"slot_release\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"container"}),
		strmangle.WhereClause("\"", "\"", 2, slotReleasePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.Container, o.Segment}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.Container = related.ID

	if o.R == nil {
		o.R = &slotReleaseR{
			Container: related,
		}
	} else {
		o.R.Container = related
	}

	if related.R == nil {
		related.R = &containerR{
			SlotReleases: SlotReleaseSlice{o},
		}
	} else {
		related.R.SlotReleases = append(related.R.SlotReleases, o)
	}

	return nil
}

// SlotReleasesG retrieves all records.
func SlotReleasesG(mods ...qm.QueryMod) slotReleaseQuery {
	return SlotReleases(boil.GetDB(), mods...)
}

// SlotReleases retrieves all the records using an executor.
func SlotReleases(exec boil.Executor, mods ...qm.QueryMod) slotReleaseQuery {
	mods = append(mods, qm.From("\"slot_release\""))
	return slotReleaseQuery{NewQuery(exec, mods...)}
}

// FindSlotReleaseG retrieves a single record by ID.
func FindSlotReleaseG(container int, segment custom_types.Segment, selectCols ...string) (*SlotRelease, error) {
	return FindSlotRelease(boil.GetDB(), container, segment, selectCols...)
}

// FindSlotReleaseGP retrieves a single record by ID, and panics on error.
func FindSlotReleaseGP(container int, segment custom_types.Segment, selectCols ...string) *SlotRelease {
	retobj, err := FindSlotRelease(boil.GetDB(), container, segment, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindSlotRelease retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSlotRelease(exec boil.Executor, container int, segment custom_types.Segment, selectCols ...string) (*SlotRelease, error) {
	slotReleaseObj := &SlotRelease{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"slot_release\" where \"container\"=$1 AND \"segment\"=$2", sel,
	)

	q := queries.Raw(exec, query, container, segment)

	err := q.Bind(slotReleaseObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "public: unable to select from slot_release")
	}

	return slotReleaseObj, nil
}

// FindSlotReleaseP retrieves a single record by ID with an executor, and panics on error.
func FindSlotReleaseP(exec boil.Executor, container int, segment custom_types.Segment, selectCols ...string) *SlotRelease {
	retobj, err := FindSlotRelease(exec, container, segment, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *SlotRelease) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *SlotRelease) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *SlotRelease) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *SlotRelease) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("public: no slot_release provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(slotReleaseColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	slotReleaseInsertCacheMut.RLock()
	cache, cached := slotReleaseInsertCache[key]
	slotReleaseInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			slotReleaseColumns,
			slotReleaseColumnsWithDefault,
			slotReleaseColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(slotReleaseType, slotReleaseMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(slotReleaseType, slotReleaseMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"slot_release\" (\"%s\") VALUES (%s)", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"slot_release\" DEFAULT VALUES"
		}

		if len(cache.retMapping) != 0 {
			cache.query += fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "public: unable to insert into slot_release")
	}

	if !cached {
		slotReleaseInsertCacheMut.Lock()
		slotReleaseInsertCache[key] = cache
		slotReleaseInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single SlotRelease record. See Update for
// whitelist behavior description.
func (o *SlotRelease) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single SlotRelease record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *SlotRelease) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the SlotRelease, and panics on error.
// See Update for whitelist behavior description.
func (o *SlotRelease) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the SlotRelease.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *SlotRelease) Update(exec boil.Executor, whitelist ...string) error {
	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	slotReleaseUpdateCacheMut.RLock()
	cache, cached := slotReleaseUpdateCache[key]
	slotReleaseUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(slotReleaseColumns, slotReleasePrimaryKeyColumns, whitelist)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("public: unable to update slot_release, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"slot_release\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, slotReleasePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(slotReleaseType, slotReleaseMapping, append(wl, slotReleasePrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "public: unable to update slot_release row")
	}

	if !cached {
		slotReleaseUpdateCacheMut.Lock()
		slotReleaseUpdateCache[key] = cache
		slotReleaseUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q slotReleaseQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q slotReleaseQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "public: unable to update all for slot_release")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o SlotReleaseSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o SlotReleaseSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o SlotReleaseSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SlotReleaseSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("public: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), slotReleasePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	query := fmt.Sprintf(
		"UPDATE \"slot_release\" SET %s WHERE (\"container\",\"segment\") IN (%s)",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.Placeholders(dialect.IndexPlaceholders, len(o)*len(slotReleasePrimaryKeyColumns), len(colNames)+1, len(slotReleasePrimaryKeyColumns)),
	)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(query, args...)
	if err != nil {
		return errors.Wrap(err, "public: unable to update all in slotRelease slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *SlotRelease) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *SlotRelease) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *SlotRelease) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *SlotRelease) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("public: no slot_release provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(slotReleaseColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	slotReleaseUpsertCacheMut.RLock()
	cache, cached := slotReleaseUpsertCache[key]
	slotReleaseUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		var ret []string
		whitelist, ret = strmangle.InsertColumnSet(
			slotReleaseColumns,
			slotReleaseColumnsWithDefault,
			slotReleaseColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)
		update := strmangle.UpdateColumnSet(
			slotReleaseColumns,
			slotReleasePrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("public: unable to upsert slot_release, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(slotReleasePrimaryKeyColumns))
			copy(conflict, slotReleasePrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"slot_release\"", updateOnConflict, ret, update, conflict, whitelist)

		cache.valueMapping, err = queries.BindMapping(slotReleaseType, slotReleaseMapping, whitelist)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(slotReleaseType, slotReleaseMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "public: unable to upsert slot_release")
	}

	if !cached {
		slotReleaseUpsertCacheMut.Lock()
		slotReleaseUpsertCache[key] = cache
		slotReleaseUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single SlotRelease record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *SlotRelease) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single SlotRelease record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *SlotRelease) DeleteG() error {
	if o == nil {
		return errors.New("public: no SlotRelease provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single SlotRelease record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *SlotRelease) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single SlotRelease record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *SlotRelease) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("public: no SlotRelease provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), slotReleasePrimaryKeyMapping)
	query := "DELETE FROM \"slot_release\" WHERE \"container\"=$1 AND \"segment\"=$2"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(query, args...)
	if err != nil {
		return errors.Wrap(err, "public: unable to delete from slot_release")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q slotReleaseQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q slotReleaseQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("public: no slotReleaseQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "public: unable to delete all from slot_release")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o SlotReleaseSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o SlotReleaseSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("public: no SlotRelease slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o SlotReleaseSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SlotReleaseSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("public: no SlotRelease slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(slotReleaseBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), slotReleasePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	query := fmt.Sprintf(
		"DELETE FROM \"slot_release\" WHERE (%s) IN (%s)",
		strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, slotReleasePrimaryKeyColumns), ","),
		strmangle.Placeholders(dialect.IndexPlaceholders, len(o)*len(slotReleasePrimaryKeyColumns), 1, len(slotReleasePrimaryKeyColumns)),
	)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(query, args...)
	if err != nil {
		return errors.Wrap(err, "public: unable to delete all from slotRelease slice")
	}

	if len(slotReleaseAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *SlotRelease) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *SlotRelease) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *SlotRelease) ReloadG() error {
	if o == nil {
		return errors.New("public: no SlotRelease provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *SlotRelease) Reload(exec boil.Executor) error {
	ret, err := FindSlotRelease(exec, o.Container, o.Segment)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *SlotReleaseSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *SlotReleaseSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SlotReleaseSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("public: empty SlotReleaseSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SlotReleaseSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slotReleases := SlotReleaseSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), slotReleasePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	query := fmt.Sprintf(
		"SELECT \"slot_release\".* FROM \"slot_release\" WHERE (%s) IN (%s)",
		strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, slotReleasePrimaryKeyColumns), ","),
		strmangle.Placeholders(dialect.IndexPlaceholders, len(*o)*len(slotReleasePrimaryKeyColumns), 1, len(slotReleasePrimaryKeyColumns)),
	)

	q := queries.Raw(exec, query, args...)

	err := q.Bind(&slotReleases)
	if err != nil {
		return errors.Wrap(err, "public: unable to reload all in SlotReleaseSlice")
	}

	*o = slotReleases

	return nil
}

// SlotReleaseExists checks if the SlotRelease row exists.
func SlotReleaseExists(exec boil.Executor, container int, segment custom_types.Segment) (bool, error) {
	var exists bool

	query := "select exists(select 1 from \"slot_release\" where \"container\"=$1 AND \"segment\"=$2 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, container, segment)
	}

	row := exec.QueryRow(query, container, segment)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "public: unable to check if slot_release exists")
	}

	return exists, nil
}

// SlotReleaseExistsG checks if the SlotRelease row exists.
func SlotReleaseExistsG(container int, segment custom_types.Segment) (bool, error) {
	return SlotReleaseExists(boil.GetDB(), container, segment)
}

// SlotReleaseExistsGP checks if the SlotRelease row exists. Panics on error.
func SlotReleaseExistsGP(container int, segment custom_types.Segment) bool {
	e, err := SlotReleaseExists(boil.GetDB(), container, segment)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// SlotReleaseExistsP checks if the SlotRelease row exists. Panics on error.
func SlotReleaseExistsP(exec boil.Executor, container int, segment custom_types.Segment) bool {
	e, err := SlotReleaseExists(exec, container, segment)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
