FROM databrary-base

WORKDIR Schemabrary
RUN stack build
RUN stack exec schemabrary -- -c /tmp/databrary_config/databrary.conf

WORKDIR ../
RUN npm install
RUN npm update
RUN `npm root`/.bin/bower update

RUN stack build
RUN stack exec databrary -- -w

