FROM databrary_databrary:base

RUN npm install
RUN npm update
RUN `npm root`/.bin/bower update

# prep for schema construction
WORKDIR Schemabrary
RUN git pull origin build_system && stack build
RUN stack exec schemabrary -- -c databrary.conf
WORKDIR /home/databrary/src
