// Package xo_models contains the types for schema 'public'.
package xo_models

import "github.com/databrary/sqlboiler/boil"

// GENERATED BY XO. DO NOT EDIT.

// RecordDaterange calls the stored procedure 'public.record_daterange(integer) daterange' on db.
func RecordDaterange(exec boil.Executor, v0 int) (custom_types.Daterange, error) {
	var err error

	// sql query
	const query = `SELECT public.record_daterange($1)`

	// run query
	var ret custom_types.Daterange

	err = exec.QueryRow(query, v0).Scan(&ret)
	if err != nil {
		return custom_types.Daterange{}, err
	}

	return ret, nil
}
