// Package xo_models contains the types for schema 'public'.
package xo_models

import "github.com/databrary/sqlboiler/boil"

// GENERATED BY XO. DO NOT EDIT.

// VolumeAccessCheck calls the stored procedure 'public.volume_access_check(integer, integer) permission' on db.
func VolumeAccessCheck(exec boil.Executor, v0 int, v1 int) (Permission, error) {
	var err error

	// sql query
	const query = `SELECT public.volume_access_check($1, $2)`

	// run query
	var ret Permission

	err = exec.QueryRow(query, v0, v1).Scan(&ret)
	if err != nil {
		return Permission{}, err
	}

	return ret, nil
}
